### ISSUE TITLE
gd script dependencies

### ISSUE THREAD

**Issue by daerogami** [CapsCollective/godot-actions#2]
I looked around and couldn't figure out where `scripts/apply_version.gd` is sourced from. Also, is this a stand-alone script or should this be in my godot project's `scripts` folder? because my project is inside a folder named `src`, so unless there is a way to tell the `Apply version to export information` step to change its working directory, there are file path assumptions that won't work with my project being inside a folder instead of the root of the repo.

**Comment by daerogami** [comment]
Created PR #3 to address the path concern. I referenced https://github.com/CapsCollective/rng-stronghold/tree/develop to get the dependent scripts. I have concerns that this action has gd script dependencies. It might make sense to pull them out of the build step and note that the build action assumes those 4 application/*version parameters need to be set. The extract version is its own action, maybe that should be as well?

**Comment by jonjondev** [comment]
Thanks for submitting the PR for the base path changes - that is a definite improvement. Yes, the `apply_version.gd ` script inclusion was an oversight when splitting out of the game repos. I may just move that particular line into the project workflow and remove it from here. I will let you know the result.

**Comment by jonjondev** [comment]
The solution above has been applied and will be part of the changes included in `v1.2`.
